### ISSUE TITLE
Macro expand?

### ISSUE THREAD

**Issue by batate** [narrowtux/loppers#6]
Thanks for a cool project. 

Question. Should the AST be run through Macro.expand/2 before validating? Or is that outside the scope of the project? 

If you would like, I can take a shot at this and support a pr.

**Comment by narrowtux** [comment]
This depends on how you want to use the black/whitelist - I wouldn't build this into the project however, since it would break a lot of assumptions.

I'd only pass the AST through Macro.expand in case I'm not trusting my Macros not to do bad things.

Also note that if you use a whitelist-only approach (like I do where I use this library), the whitelist has to be a lot bigger to make possible anything that the called macros do.

In a blacklist approach it could make sense though.

**Comment by narrowtux** [comment]
As this library does not actually compile source code, I would also not build an option to call Macro.expand because it can be easily done in the code where you compile the code and call the validate function.

**Comment by batate** [comment]
Thanks for the quick response.
